export type RestMethod = "GET" | "POST" | "PUT" | "DELETE";

export interface RestEndpoint {
  method: RestMethod;
  path: string;
  group: string;
  write: boolean;
}

export const CONFLUENCE_7_13_7_ENDPOINTS = [
  { method: "GET", path: "/accessmode", group: "accessmode", write: false },
  { method: "GET", path: "/audit", group: "audit", write: false },
  { method: "POST", path: "/audit", group: "audit", write: true },
  { method: "GET", path: "/audit/export", group: "audit", write: false },
  { method: "GET", path: "/audit/retention", group: "audit", write: false },
  { method: "PUT", path: "/audit/retention", group: "audit", write: true },
  { method: "GET", path: "/audit/since", group: "audit", write: false },
  { method: "GET", path: "/content", group: "content", write: false },
  { method: "POST", path: "/content", group: "content", write: true },
  { method: "GET", path: "/content/search", group: "content", write: false },
  { method: "POST", path: "/content/blueprint/instance/{draftId}", group: "content", write: true },
  { method: "PUT", path: "/content/blueprint/instance/{draftId}", group: "content", write: true },
  { method: "PUT", path: "/content/{contentId}", group: "content", write: true },
  { method: "GET", path: "/content/{id}", group: "content", write: false },
  { method: "DELETE", path: "/content/{id}", group: "content", write: true },
  { method: "GET", path: "/content/{id}/child", group: "content-child", write: false },
  { method: "GET", path: "/content/{id}/child/attachment", group: "attachment", write: false },
  { method: "POST", path: "/content/{id}/child/attachment", group: "attachment", write: true },
  { method: "PUT", path: "/content/{id}/child/attachment/{attachmentId}", group: "attachment", write: true },
  { method: "POST", path: "/content/{id}/child/attachment/{attachmentId}/data", group: "attachment", write: true },
  { method: "GET", path: "/content/{id}/child/comment", group: "content-child", write: false },
  { method: "GET", path: "/content/{id}/child/{type}", group: "content-child", write: false },
  { method: "GET", path: "/content/{id}/descendant", group: "content-descendant", write: false },
  { method: "GET", path: "/content/{id}/descendant/{type}", group: "content-descendant", write: false },
  { method: "GET", path: "/content/{id}/history", group: "content-history", write: false },
  { method: "GET", path: "/content/{id}/history/{version}/macro/hash/{hash}", group: "content-macro", write: false },
  { method: "GET", path: "/content/{id}/history/{version}/macro/id/{macroId}", group: "content-macro", write: false },
  { method: "GET", path: "/content/{id}/label", group: "label", write: false },
  { method: "POST", path: "/content/{id}/label", group: "label", write: true },
  { method: "DELETE", path: "/content/{id}/label", group: "label", write: true },
  { method: "DELETE", path: "/content/{id}/label/{label}", group: "label", write: true },
  { method: "GET", path: "/content/{id}/property", group: "content-property", write: false },
  { method: "POST", path: "/content/{id}/property", group: "content-property", write: true },
  { method: "POST", path: "/content/{id}/property/{key}", group: "content-property", write: true },
  { method: "GET", path: "/content/{id}/property/{key}", group: "content-property", write: false },
  { method: "PUT", path: "/content/{id}/property/{key}", group: "content-property", write: true },
  { method: "DELETE", path: "/content/{id}/property/{key}", group: "content-property", write: true },
  { method: "GET", path: "/content/{id}/restriction/byOperation", group: "restriction", write: false },
  { method: "GET", path: "/content/{id}/restriction/byOperation/{operationKey}", group: "restriction", write: false },
  { method: "POST", path: "/contentbody/convert/{to}", group: "contentbody", write: true },
  { method: "GET", path: "/group", group: "group", write: false },
  { method: "GET", path: "/group/{groupName}", group: "group", write: false },
  { method: "GET", path: "/group/{groupName}/member", group: "group", write: false },
  { method: "GET", path: "/longtask", group: "longtask", write: false },
  { method: "GET", path: "/longtask/{id}", group: "longtask", write: false },
  { method: "GET", path: "/search", group: "search", write: false },
  { method: "GET", path: "/space", group: "space", write: false },
  { method: "POST", path: "/space", group: "space", write: true },
  { method: "POST", path: "/space/_private", group: "space", write: true },
  { method: "GET", path: "/space/{spaceKey}", group: "space", write: false },
  { method: "PUT", path: "/space/{spaceKey}", group: "space", write: true },
  { method: "DELETE", path: "/space/{spaceKey}", group: "space", write: true },
  { method: "GET", path: "/space/{spaceKey}/content", group: "space-content", write: false },
  { method: "GET", path: "/space/{spaceKey}/content/{type}", group: "space-content", write: false },
  { method: "GET", path: "/space/{spaceKey}/property", group: "space-property", write: false },
  { method: "POST", path: "/space/{spaceKey}/property", group: "space-property", write: true },
  { method: "POST", path: "/space/{spaceKey}/property/{key}", group: "space-property", write: true },
  { method: "GET", path: "/space/{spaceKey}/property/{key}", group: "space-property", write: false },
  { method: "PUT", path: "/space/{spaceKey}/property/{key}", group: "space-property", write: true },
  { method: "DELETE", path: "/space/{spaceKey}/property/{key}", group: "space-property", write: true },
  { method: "GET", path: "/user", group: "user", write: false },
  { method: "GET", path: "/user/anonymous", group: "user", write: false },
  { method: "GET", path: "/user/current", group: "user", write: false },
  { method: "GET", path: "/user/memberof", group: "user", write: false },
  { method: "POST", path: "/user/watch/content/{contentId}", group: "watch", write: true },
  { method: "GET", path: "/user/watch/content/{contentId}", group: "watch", write: false },
  { method: "DELETE", path: "/user/watch/content/{contentId}", group: "watch", write: true },
  { method: "POST", path: "/user/watch/space/{spaceKey}", group: "watch", write: true },
  { method: "GET", path: "/user/watch/space/{spaceKey}", group: "watch", write: false },
  { method: "DELETE", path: "/user/watch/space/{spaceKey}", group: "watch", write: true },
  { method: "GET", path: "/webhooks", group: "webhooks", write: false },
  { method: "POST", path: "/webhooks", group: "webhooks", write: true },
  { method: "GET", path: "/webhooks/{webhookId}", group: "webhooks", write: false },
  { method: "PUT", path: "/webhooks/{webhookId}", group: "webhooks", write: true },
  { method: "DELETE", path: "/webhooks/{webhookId}", group: "webhooks", write: true },
  { method: "GET", path: "/webhooks/{webhookId}/latest", group: "webhooks", write: false },
  { method: "GET", path: "/webhooks/{webhookId}/statistics", group: "webhooks", write: false },
  { method: "GET", path: "/webhooks/{webhookId}/statistics/summary", group: "webhooks", write: false },
  { method: "POST", path: "/webhooks/test", group: "webhooks", write: true },
] as const satisfies readonly RestEndpoint[];

export function findEndpoint(method: RestMethod, path: string): RestEndpoint | undefined {
  return CONFLUENCE_7_13_7_ENDPOINTS.find((endpoint) => endpoint.method === method && endpoint.path === path);
}
